package com.city.blog.blog.model;

public class BlogUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER.ID
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER.NAME
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER.TOKEN
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER.GMT_CREATE
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER.GMT_MODIFIED
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER.AVATAR_URL
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER.PASSWORD
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER.ID
     *
     * @return the value of BLOG_USER.ID
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER.ID
     *
     * @param id the value for BLOG_USER.ID
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER.NAME
     *
     * @return the value of BLOG_USER.NAME
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER.NAME
     *
     * @param name the value for BLOG_USER.NAME
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER.TOKEN
     *
     * @return the value of BLOG_USER.TOKEN
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER.TOKEN
     *
     * @param token the value for BLOG_USER.TOKEN
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER.GMT_CREATE
     *
     * @return the value of BLOG_USER.GMT_CREATE
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER.GMT_CREATE
     *
     * @param gmtCreate the value for BLOG_USER.GMT_CREATE
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER.GMT_MODIFIED
     *
     * @return the value of BLOG_USER.GMT_MODIFIED
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER.GMT_MODIFIED
     *
     * @param gmtModified the value for BLOG_USER.GMT_MODIFIED
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER.AVATAR_URL
     *
     * @return the value of BLOG_USER.AVATAR_URL
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER.AVATAR_URL
     *
     * @param avatarUrl the value for BLOG_USER.AVATAR_URL
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER.PASSWORD
     *
     * @return the value of BLOG_USER.PASSWORD
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER.PASSWORD
     *
     * @param password the value for BLOG_USER.PASSWORD
     *
     * @mbg.generated Fri May 15 12:53:08 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}